name: my_tflit_app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "3.5.4"



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.9
  flutter_tflite: ^1.0.1
  archive: 
  collection: ^1.16.0
  image: 
  path_provider: ^2.0.11
  logger: ^2.5.0

  url_launcher: ^6.1.11
  page_transition: ^2.0.9
  animated_splash_screen: ^1.3.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_messaging: ^15.1.6
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.5.1
  fluttertoast: ^8.2.4
  icons_plus: ^5.0.0
  curved_navigation_bar: ^1.0.3
  firebase_database: ^11.2.0
  provider: ^6.0.5
  intl:
  uuid:
  shared_preferences: ^2.2.0
  flutter_localizations:
    sdk: flutter
  quiver: ^3.2.2
  image_gallery_saver_plus: ^3.0.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: SquadaOne
      fonts:
        - asset: assets/SquadaOne-Regular.ttf
    - family: ContrailOne
      fonts:
        - asset: assets/ContrailOne-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/Roboto-Light.ttf

  assets:
    - assets/

  